### PR TITLE
Support calling other functions

### PR DESCRIPTION
**Pull request by ixahedron**
Problem: we can always run only one single function, but not invoke other functions.

Solution: implemented `call` and `return` by overhauling half the codebase. See individual commits for more description.

NB: while we already had some differences (in opinion) with the WebAssembly spec, this deviates from it even further, including not having activation frames on stack at all. This may or may not spring a trap on us in the future :D

### CODE REVIEW

**Comment by cognivore** [comment]
First 3 commits lgtm! Commit messages are amazing. Even the "why not inductive" defused 😃

**Comment by cognivore** [comment]
Commit 4 looks good.

**Comment by cognivore** [comment]
Commit 5 looks good. Can't argue with tests! 

Also excited about the additional tests it will allow me to bring into my test suite.

**Comment by cognivore** [comment]
Commit 6 *feels* bad but looks good.

Good thing that our users (as in, developers who use or modify lean wasm runtime) won't need to count lifts themselves because you provide convenience functions.

**Review by cognivore — APPROVED** [review]
LGTM

**Comment by cognivore** [comment]
> while we already had some differences (in opinion) with the WebAssembly spec, this deviates from it even further, including not having activation frames on stack at all. This may or may not spring a trap on us in the future

I think it's ok as long as we're compatible for all the programs we want to support.

**Comment by ixahedron** [comment]
> 

Totally feels bad. IDK, maybe we'll come up with a better solution in the future :/

**Pull request merged**
